### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by sxdeivm** [zhysora/PSGan-Family#14]
您好，请问Raw文件夹应该怎么制作，下载的数据集中没有Raw文件夹。具体报错如下：
ERROR 4: `/data/zh/PSData/Raw/WV-2/1-MUL.TIF' does not exist in the file system, and is not recognized as a supported dataset name.
Traceback (most recent call last):
  File "F:\PSGan-Family-master\data\handle_raw.py", line 42, in <module>
    rawMul = gdal.Open( '%s/Raw/%s/%d-MUL.TIF' % (dataDir, satellite, i) ).ReadAsArray()
AttributeError: 'NoneType' object has no attribute 'ReadAsArray'
非常感谢您的回答。

**Comment by zhysora** [comment]
README中有原始图像的下载链接，下载后解压放到相应文件夹下即可

**Comment by sxdeivm** [comment]
那个文件夹下也没有raw啊

**Comment by sxdeivm** [comment]
我放到对应文件夹了，可还是同样的错误，求求了帮帮孩子吧（感谢）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月25日(星期三) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14)





 
README中有原始图像的下载链接，下载后解压放到相应文件夹下即可

**Comment by zhysora** [comment]
修改对应的handle_raw.py的路径代码即可

**Comment by sxdeivm** [comment]
谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14)





 
修改对应的handle_raw.py的路径代码即可

**Comment by sxdeivm** [comment]
请问最终的融合结果图（.tif）应该咋生成呢，还有融合结果的输入和输出分别是什么呢,感谢您的回答！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14)





 
修改对应的handle_raw.py的路径代码即可

**Comment by zhysora** [comment]
可以参照README中“Train and Test the Models”章节进行模型的训练与测试。
融合结果的输入就是多光谱图像和对应的全色图像，输出是融合后的高分辨率多光谱图像。

**Comment by sxdeivm** [comment]
好的呢，融合后会生成一张.tif的图像是吧（run.py没看太懂）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14)





 
可以参照README中“Train and Test the Models”章节进行模型的训练与测试。
 融合结果的输入就是多光谱图像和对应的全色图像，输出是融合后的高分辨率多光谱图像。

**Comment by zhysora** [comment]
就是与数据集对应的若干张.tif图像

**Comment by sxdeivm** [comment]
好的呢，data\zh\PSData\Raw\GF-1中的这些数据要怎样得到呢，这些数据是不同地区的图像吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14)





 
就是与数据集对应的若干张.tif图像

**Comment by sxdeivm** [comment]
运行完run.py后没有找到融合后的图像啊，融合图像应该在那个文件夹下找啊（跪谢）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhysora/PSGan-Family"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14)





 
就是与数据集对应的若干张.tif图像

**Comment by Jamesdebaba** [comment]
请问您调通了吗，我数据集构建好了，但是运行run.py没有结果，并且log文件显示系统找不到指定路径

**Comment by bingkun99** [comment]
> 请问您调通了吗，我数据集构建好了，但是运行run.py没有结果，并且log文件显示系统找不到指定路径

您好，我最近也在看PSgan的代码，作者给出的原始数据，制作数据集的话，是直接按照代码进行切割，还是需要经过滤波矫正之类的操作在进行切割，然后to_patch。希望您能给我解答一下。刚开始学习这方面知识，如有冒犯请见谅！

**Comment by bingkun99** [comment]
> 您好，我最近也在看PSgan的代码，作者给出的原始数据，制作数据集的话，是直接按照代码进行切割，还是需要经过滤波矫正之类的操作在进行切割，然后to_patch。希望您能给我解答一下。刚开始学习这方面知识，如有冒犯请见谅！



> 运行完run.py后没有找到融合后的图像啊，融合图像应该在那个文件夹下找啊（跪谢）
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhysora/PSGan-Family" ***@***.***&gt;; 发送时间:&nbsp;2023年4月4日(星期二) 下午4:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhysora/PSGan-Family] 数据集问题 (Issue #14) 就是与数据集对应的若干张.tif图像 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，我最近也在看PSgan的代码，作者给出的原始数据，制作数据集的话，是直接按照代码进行切割，还是需要经过滤波矫正之类的操作在进行切割，然后to_patch。希望您能给我解答一下。刚开始学习这方面知识，如有冒犯请见谅！

**Comment by bingkun99** [comment]
> 您好，请问Raw文件夹应该怎么制作，下载的数据集中没有Raw文件夹。具体报错如下： ERROR 4: `/data/zh/PSData/Raw/WV-2/1-MUL.TIF' does not exist in the file system, and is not recognized as a supported dataset name. Traceback (most recent call last): File "F:\PSGan-Family-master\data\handle_raw.py", line 42, in rawMul = gdal.Open( '%s/Raw/%s/%d-MUL.TIF' % (dataDir, satellite, i) ).ReadAsArray() AttributeError: 'NoneType' object has no attribute 'ReadAsArray' 非常感谢您的回答。

您好，我最近也在看PSgan的代码，作者给出的原始数据，制作数据集的话，是直接按照代码进行切割，还是需要经过滤波矫正之类的操作在进行切割，然后to_patch。希望您能给我解答一下。刚开始学习这方面知识，如有冒犯请见谅！
